# MOSTRANDO A COLUNA DE FORNECEDORES E INSERINDO VALORES
SHOW columns FROM FORNECEDORES;
INSERT INTO FORNECEDORES(FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES('10', 'UVV', 'CENTRO', '45', 'COSTA', 'VILA', 'ESPIRITO SANTO', 'BRASIL', '233749', '27 999874202','universidade');

# MOSTRANDO A COLUNA DE FILIAIS E INSERINDO VALORES
SHOW columns FROM FILIAIS;
INSERT INTO FILIAIS(FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES('18', 'Integra', 'Horizonte', '621', 'Delta', 'Vale Sereno', 'Litorânea', 'Brasil', '1839201', 'capacidade');

# MOSTRANDO A COLUNA DE PRODUTOS E INSERINDO VALORES
SHOW columns FROM PRODUTOS;
INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES('213', 'Tablet', 'Tablet Alpha SkyView', 'Tablet AV', '75', '380.00', '500g', '50');

# MOSTRANDO A COLUNA DE PEDIDOS E INSERINDO VALORES
SHOW columns FROM PEDIDOS;
INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES('94', '2024-09-24', '15:02:09', '2024-10-01', 'EM ESPERA', '10');

# MOSTRANDO A COLUNA DE RECEBIMENTOS E INSERINDO VALORES
SHOW columns FROM RECEBIMENTOS;
INSERT INTO RECEBIMENTOS(RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES('2024-10-10', '18:10:02','10.022', 'Adequado','94');
