#ALTERANDO TABELA FORNECEDORES
ALTER TABLE FORNECEDORES 
ADD FORNEC_EMAIL VARCHAR(60);
ALTER TABLE FORNECEDORES 
DROP COLUMN FORNEC_EMAIL;
ALTER TABLE FORNECEDORES 
MODIFY COLUMN FORNEC_NOME VARCHAR(60) NOT NULL;
ALTER TABLE FORNECEDORES 
CHANGE COLUMN FORNEC_NUMRUA FORNEC_NUM_RUA INT;

#ALTERANDO TABELA FILIAIS
ALTER TABLE FILIAIS 
DROP COLUMN FILIAL_CODPOSTAL;
ALTER TABLE FILIAIS 
ADD FILIAl_CEP VARCHAR(14);
ALTER TABLE FILIAIS 
MODIFY COLUMN FILIAL_RUA VARCHAR(80) NOT NULL;
ALTER TABLE FILIAIS 
CHANGE COLUMN FILIAL_CAPACIDADE FILIAL_CAPACI TEXT NOT NULL;

#ALTERANDO TABELA PRODUTOS
ALTER TABLE PRODUTOS 
MODIFY COLUMN PROD_UNIDMEDIDA VARCHAR(20) NOT NULL;
ALTER TABLE PRODUTOS 
DROP COLUMN PROD_PRECOUNIT;
ALTER TABLE PRODUTOS 
CHANGE COLUMN PROD_QUANT PROD_QUANTIDADE DECIMAL(10,3) NOT NULL;
ALTER TABLE PRODUTOS 
ADD PROD_ORIGEM TEXT NOT NULL;

#removendo o est_caso_i
DROP DATABASE EST_CASO_I;