USE EST_CASO_I;

# MOSTRANDO A COLUNA DE FORNECEDORES E INSERINDO VALORES
SHOW columns FROM FORNECEDORES;
INSERT INTO FORNECEDORES(FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO)
VALUES('10', 'UVV', 'CENTRO', '45', 'COSTA', 'VILA', 'ESPIRITO SANTO', 'BRASIL', '233749', '27 999874202','universidade');
#
UPDATE FORNECEDORES
SET FORNEC_NOME = 'Fornecedor Atualizado', FORNEC_TELEFONE = '123456789'
WHERE FORNEC_COD = 1;
UPDATE FORNECEDORES
SET FORNEC_CIDADE = 'Nova Cidade', FORNEC_ESTADO = 'SP'
WHERE FORNEC_COD = 2;
#
DELETE FROM FORNECEDORES
WHERE FORNEC_COD = 1;


# MOSTRANDO A COLUNA DE FILIAIS E INSERINDO VALORES
SHOW columns FROM FILIAIS;
INSERT INTO FILIAIS(FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE)
VALUES('18', 'Integra', 'Horizonte', '621', 'Delta', 'Vale Sereno', 'Litorânea', 'Brasil', '1839201', 'capacidade');
#
UPDATE FILIAIS
SET FILIAL_NOME = 'Filial Atualizada', FILIAL_CAPACIDADE = 'Alta'
WHERE FILIAL_COD = 1;
UPDATE FILIAIS
SET FILIAL_ESTADO = 'RJ', FILIAL_PAIS = 'Brasil'
WHERE FILIAL_COD = 2;
#
DELETE FROM FILIAIS
WHERE FILIAL_COD = 2;


# MOSTRANDO A COLUNA DE PRODUTOS E INSERINDO VALORES
SHOW columns FROM PRODUTOS;
INSERT INTO PRODUTOS(PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES('213', 'Tablet', 'Tablet Alpha SkyView', 'Tablet AV', '75', '380.00', '500g', '50');
#
UPDATE PRODUTOS
SET PROD_PRECOUNIT = 15.50, PROD_QUANT = 100.0
WHERE PROD_COD = 1;
UPDATE PRODUTOS
SET PROD_ESTOQ_MIN = 20.0, PROD_UNIDMEDIDA = 'UN'
WHERE PROD_COD = 2;
#
DELETE FROM PRODUTOS
WHERE PROD_COD = 3;


# MOSTRANDO A COLUNA DE PEDIDOS E INSERINDO VALORES
SHOW columns FROM PEDIDOS;
INSERT INTO PEDIDOS(PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR)
VALUES('94', '2024-09-24', '15:02:09', '2024-10-01', 'EM ESPERA', '10');
#
UPDATE PEDIDOS
SET PED_STATUS = 'CONCLUÍDO', PED_PREVISAO = '2024-11-15'
WHERE PED_CODIGO = 1;
#Alterando a um pedido específico
UPDATE PEDIDOS
SET PED_DATA = '2024-10-30', PED_HORA = '10:30:00'
WHERE PED_CODIGO = 2;
#
DELETE FROM PEDIDOS
WHERE PED_CODIGO = 4;


# MOSTRANDO A COLUNA DE RECEBIMENTOS E INSERINDO VALORES
SHOW columns FROM RECEBIMENTOS;
INSERT INTO RECEBIMENTOS(RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES('2024-10-10', '18:10:02','10.022', 'Adequado','94');
#
UPDATE RECEBIMENTOS
SET RECEB_QUANT_PROD = 50.0, RECEB_CONDICAO = 'Bom'
WHERE RECEB_PEDIDOS = 1;
#Alterar a data e hora de um recebimento específico
UPDATE RECEBIMENTOS
SET RECEB_DATA = '2024-10-30', RECEB_HORA = '14:00:00'
WHERE RECEB_PEDIDOS = 2;
#
DELETE FROM RECEBIMENTOS
WHERE RECEB_PEDIDOS = 4;


#TABELA PEDIDOS_PRODUTOS
UPDATE PEDIDOS_PRODUTOS
SET PDPR_QUANT = 30.0
WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 2;
UPDATE PEDIDOS_PRODUTOS
SET PDPR_QUANT = 15.0
WHERE PDPR_PEDIDOS = 2 AND PDPR_PRODUTOS = 3;
#
DELETE FROM PEDIDOS_PRODUTOS
WHERE PDPR_PEDIDOS = 4 AND PDPR_PRODUTOS = 3;


#TABELA FILAIS_PRODUTOS
UPDATE FILIAIS_PRODUTOS
SET FLPR_QUANT = 40.0
WHERE FLPR_FILIAL = 1 AND FLPR_PRODUTOS = 2;
UPDATE FILIAIS_PRODUTOS
SET FLPR_QUANT = 25.0
WHERE FLPR_FILIAL = 2 AND FLPR_PRODUTOS = 3;
#
DELETE FROM FILIAIS_PRODUTOS
WHERE FLPR_FILIAL = 2 AND FLPR_PRODUTOS = 3;


#TABELA FORNECEDORES_PRODUTOS
UPDATE FORNECEDORES_PRODUTOS
SET FRPR_FORNECEDOR = 3
WHERE FRPR_PRODUTOS = 2;
UPDATE FORNECEDORES_PRODUTOS
SET FRPR_FORNECEDOR = 4
WHERE FRPR_PRODUTOS = 3;
#
DELETE FROM FORNECEDORES_PRODUTOS
WHERE FRPR_FORNECEDOR = 1 AND FRPR_PRODUTOS = 3;
